export type { Profile, UserRole, UserFilters } from "./users";
export type {
  Curso,
  Materia,
  Unidad,
  Tema,
  Leccion,
  RecentContentItem,
  LeccionSeccion,
  Foro,
  ForoHilo,
  ForoMensaje,
  LeccionVideoProgreso,
  LeccionSeccionGatingPDF,
  ActividadInteractiva,
  ActividadInteractivaIntento,
  MateriaSeguimiento,
  EstudianteCursoDetail,
  DocenteMateriaAsignacion,
  MisCursoDocente,
  CursoAnioMateriaDocenteInput,
  CursoAnioAsignarMaestrosRequest,
  CursoAnioAsignarMaestrosDetalle,
  CursoAnioAsignarMaestrosResult,
  MateriaCalificacionAlumno,
  MateriaCalificacionesResponse,
  MateriaCalificacionEstudianteResponse,
  StudentGradeDetailTipo,
  StudentGradeDetailEstado,
  StudentGradeDetailItem,
  StudentGradeTypeAggregate,
  StudentGradeMateriaAggregate,
  StudentGradeUnidadAggregate,
  StudentGradeTemaAggregate,
  StudentGradeAggregates,
  StudentGradeDetailResponse,
  StudentGradeFilters,
  TeacherGradeDetailTipo,
  TeacherGradeDetailEstado,
  TeacherGradeDetailItem,
  TeacherGradeTypeAggregate,
  TeacherGradeCursoAggregate,
  TeacherGradeMateriaAggregate,
  TeacherGradeEstudianteAggregate,
  TeacherGradeUnidadAggregate,
  TeacherGradeTemaAggregate,
  TeacherGradeAggregates,
  TeacherGradeDetailResponse,
  TeacherGradeFilters,
} from "./academic";
export type { Recurso, ModeloRA } from "./resources";
export type {
  Prueba,
  PruebaConLeccion,
  Pregunta,
  Respuesta,
  ResultadoPrueba,
  Progreso,
  ProgresoSeccion,
  PruebaCompleta,
} from "./evaluations";
export type {
  EstadoTrabajo,
  EstadoEntregaTrabajo,
  Trabajo,
  TrabajoEntrega,
  TrabajoCalificacion,
  TrabajoConEstadoEntrega,
  EntregaConCalificacion,
  CreateTrabajoRequest,
  CreateEntregaRequest,
  CalificarEntregaRequest,
} from "./trabajos";
