export type { Profile, UserRole, UserFilters } from "./users";
export type {
  Curso,
  Materia,
  Unidad,
  Tema,
  Leccion,
  RecentContentItem,
  LeccionSeccion,
  Foro,
  ForoHilo,
  ForoMensaje,
  LeccionVideoProgreso,
  LeccionSeccionGatingPDF,
  ActividadInteractiva,
  ActividadInteractivaIntento,
  MateriaSeguimiento,
  EstudianteCursoDetail,
  DocenteMateriaAsignacion,
  MisCursoDocente,
  DocenteMateriaHorario,
  DocenteMateriaHorarioRequest,
  CursoAnioMateriaDocenteInput,
  CursoAnioAsignarMaestrosRequest,
  CursoAnioAsignarMaestrosDetalle,
  CursoAnioAsignarMaestrosResult,
  MateriaCalificacionAlumno,
  MateriaCalificacionesResponse,
  MateriaCalificacionEstudianteResponse,
} from "./academic";
export type { Recurso, ModeloRA } from "./resources";
export type {
  Prueba,
  Pregunta,
  Respuesta,
  ResultadoPrueba,
  Progreso,
  ProgresoSeccion,
  PruebaCompleta,
} from "./evaluations";
export type {
  EstadoTrabajo,
  EstadoEntregaTrabajo,
  Trabajo,
  TrabajoEntrega,
  TrabajoCalificacion,
  EntregaConCalificacion,
  CreateTrabajoRequest,
  CreateEntregaRequest,
  CalificarEntregaRequest,
} from "./trabajos";
